# 应用服务 WEB 访问端口
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: false
  servlet:
    context-path: /pvs
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
# 数据库连接配置
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/pvsystem?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 5728
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/pvystemdata?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 5728
          driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
#  # Redis 连接集群
#  redis:
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.1.138:26379
#        - 192.168.1.138:26380
#        - 192.168.1.138:26381
#    password: Hust@411

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Python 脚本位置
algorithm:
  pythonFilePath: C:/data
  threshold: 0.95
logging:
  level:
    com.hust.encrypt: info


# Redis 单节点配置（如果需要，可以解开注释）
# redis:
#   host: 127.0.0.1
#   port: 6379
#   password:
#   timeout: 2000
